/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PlaneWorkspaceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMember"
      | "createWorkspace"
      | "getMemberRole"
      | "getUserWorkspaces"
      | "getWorkspace"
      | "getWorkspaceCID"
      | "getWorkspaceMembers"
      | "removeMember"
      | "updateWorkspaceCID"
      | "updateWorkspaceCIDIfMatches"
      | "workspaceExists"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MemberAdded"
      | "MemberRemoved"
      | "WorkspaceCIDUpdated"
      | "WorkspaceCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createWorkspace",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberRole",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserWorkspaces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspace",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspaceCID",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getWorkspaceMembers",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWorkspaceCID",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWorkspaceCIDIfMatches",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "workspaceExists",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserWorkspaces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspaceCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWorkspaceMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWorkspaceCID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWorkspaceCIDIfMatches",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "workspaceExists",
    data: BytesLike
  ): Result;
}

export namespace MemberAddedEvent {
  export type InputTuple = [
    slug: string,
    member: AddressLike,
    role: BigNumberish,
    addedBy: AddressLike
  ];
  export type OutputTuple = [
    slug: string,
    member: string,
    role: bigint,
    addedBy: string
  ];
  export interface OutputObject {
    slug: string;
    member: string;
    role: bigint;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [
    slug: string,
    member: AddressLike,
    removedBy: AddressLike
  ];
  export type OutputTuple = [slug: string, member: string, removedBy: string];
  export interface OutputObject {
    slug: string;
    member: string;
    removedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkspaceCIDUpdatedEvent {
  export type InputTuple = [
    slug: string,
    newCid: string,
    updatedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    slug: string,
    newCid: string,
    updatedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    slug: string;
    newCid: string;
    updatedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkspaceCreatedEvent {
  export type InputTuple = [
    slug: string,
    name: string,
    owner: AddressLike,
    ipfsCID: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    slug: string,
    name: string,
    owner: string,
    ipfsCID: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    slug: string;
    name: string;
    owner: string;
    ipfsCID: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlaneWorkspaceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PlaneWorkspaceRegistry;
  waitForDeployment(): Promise<this>;

  interface: PlaneWorkspaceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMember: TypedContractMethod<
    [slug: string, member: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;

  createWorkspace: TypedContractMethod<
    [slug: string, name: string, initialCid: string],
    [void],
    "nonpayable"
  >;

  getMemberRole: TypedContractMethod<
    [slug: string, member: AddressLike],
    [bigint],
    "view"
  >;

  getUserWorkspaces: TypedContractMethod<
    [user: AddressLike],
    [string[]],
    "view"
  >;

  getWorkspace: TypedContractMethod<
    [slug: string],
    [
      [string, string, string, bigint] & {
        name: string;
        owner: string;
        ipfsCID: string;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getWorkspaceCID: TypedContractMethod<[slug: string], [string], "view">;

  getWorkspaceMembers: TypedContractMethod<[slug: string], [string[]], "view">;

  removeMember: TypedContractMethod<
    [slug: string, member: AddressLike],
    [void],
    "nonpayable"
  >;

  updateWorkspaceCID: TypedContractMethod<
    [slug: string, newCid: string],
    [void],
    "nonpayable"
  >;

  updateWorkspaceCIDIfMatches: TypedContractMethod<
    [slug: string, expectedOldCid: string, newCid: string],
    [void],
    "nonpayable"
  >;

  workspaceExists: TypedContractMethod<[slug: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [slug: string, member: AddressLike, role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createWorkspace"
  ): TypedContractMethod<
    [slug: string, name: string, initialCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMemberRole"
  ): TypedContractMethod<[slug: string, member: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserWorkspaces"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getWorkspace"
  ): TypedContractMethod<
    [slug: string],
    [
      [string, string, string, bigint] & {
        name: string;
        owner: string;
        ipfsCID: string;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWorkspaceCID"
  ): TypedContractMethod<[slug: string], [string], "view">;
  getFunction(
    nameOrSignature: "getWorkspaceMembers"
  ): TypedContractMethod<[slug: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [slug: string, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWorkspaceCID"
  ): TypedContractMethod<[slug: string, newCid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateWorkspaceCIDIfMatches"
  ): TypedContractMethod<
    [slug: string, expectedOldCid: string, newCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "workspaceExists"
  ): TypedContractMethod<[slug: string], [boolean], "view">;

  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "WorkspaceCIDUpdated"
  ): TypedContractEvent<
    WorkspaceCIDUpdatedEvent.InputTuple,
    WorkspaceCIDUpdatedEvent.OutputTuple,
    WorkspaceCIDUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WorkspaceCreated"
  ): TypedContractEvent<
    WorkspaceCreatedEvent.InputTuple,
    WorkspaceCreatedEvent.OutputTuple,
    WorkspaceCreatedEvent.OutputObject
  >;

  filters: {
    "MemberAdded(string,address,uint8,address)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberRemoved(string,address,address)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "WorkspaceCIDUpdated(string,string,address,uint256)": TypedContractEvent<
      WorkspaceCIDUpdatedEvent.InputTuple,
      WorkspaceCIDUpdatedEvent.OutputTuple,
      WorkspaceCIDUpdatedEvent.OutputObject
    >;
    WorkspaceCIDUpdated: TypedContractEvent<
      WorkspaceCIDUpdatedEvent.InputTuple,
      WorkspaceCIDUpdatedEvent.OutputTuple,
      WorkspaceCIDUpdatedEvent.OutputObject
    >;

    "WorkspaceCreated(string,string,address,string,uint256)": TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
    WorkspaceCreated: TypedContractEvent<
      WorkspaceCreatedEvent.InputTuple,
      WorkspaceCreatedEvent.OutputTuple,
      WorkspaceCreatedEvent.OutputObject
    >;
  };
}
