/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OffchainDataRegistryInterface extends Interface {
  getFunction(
    nameOrSignature: "deleteCID" | "getCID" | "setCID" | "setCIDIfMatches"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DataUpdated"): EventFragment;

  encodeFunctionData(functionFragment: "deleteCID", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getCID",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCID",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCIDIfMatches",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "deleteCID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCIDIfMatches",
    data: BytesLike
  ): Result;
}

export namespace DataUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    keyHash: BytesLike,
    key: string,
    cid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    keyHash: string,
    key: string,
    cid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    keyHash: string;
    key: string;
    cid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OffchainDataRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): OffchainDataRegistry;
  waitForDeployment(): Promise<this>;

  interface: OffchainDataRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deleteCID: TypedContractMethod<[key: string], [void], "nonpayable">;

  getCID: TypedContractMethod<
    [user: AddressLike, key: string],
    [string],
    "view"
  >;

  setCID: TypedContractMethod<[key: string, cid: string], [void], "nonpayable">;

  setCIDIfMatches: TypedContractMethod<
    [key: string, expectedOldCid: string, newCid: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deleteCID"
  ): TypedContractMethod<[key: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCID"
  ): TypedContractMethod<[user: AddressLike, key: string], [string], "view">;
  getFunction(
    nameOrSignature: "setCID"
  ): TypedContractMethod<[key: string, cid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCIDIfMatches"
  ): TypedContractMethod<
    [key: string, expectedOldCid: string, newCid: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DataUpdated"
  ): TypedContractEvent<
    DataUpdatedEvent.InputTuple,
    DataUpdatedEvent.OutputTuple,
    DataUpdatedEvent.OutputObject
  >;

  filters: {
    "DataUpdated(address,bytes32,string,string,uint256)": TypedContractEvent<
      DataUpdatedEvent.InputTuple,
      DataUpdatedEvent.OutputTuple,
      DataUpdatedEvent.OutputObject
    >;
    DataUpdated: TypedContractEvent<
      DataUpdatedEvent.InputTuple,
      DataUpdatedEvent.OutputTuple,
      DataUpdatedEvent.OutputObject
    >;
  };
}
