/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PlaneTaskManager {
  export type TaskStruct = {
    externalId: BytesLike;
    metadataHash: BytesLike;
    creator: AddressLike;
    assignee: AddressLike;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    dueAt: BigNumberish;
    progress: BigNumberish;
    priority: BigNumberish;
    status: BigNumberish;
    deleted: boolean;
  };

  export type TaskStructOutput = [
    externalId: string,
    metadataHash: string,
    creator: string,
    assignee: string,
    createdAt: bigint,
    updatedAt: bigint,
    dueAt: bigint,
    progress: bigint,
    priority: bigint,
    status: bigint,
    deleted: boolean
  ] & {
    externalId: string;
    metadataHash: string;
    creator: string;
    assignee: string;
    createdAt: bigint;
    updatedAt: bigint;
    dueAt: bigint;
    progress: bigint;
    priority: bigint;
    status: bigint;
    deleted: boolean;
  };

  export type DailyReportStruct = {
    reportedAt: BigNumberish;
    progress: BigNumberish;
    workHash: BytesLike;
    difficultyHash: BytesLike;
    evidenceHash: BytesLike;
  };

  export type DailyReportStructOutput = [
    reportedAt: bigint,
    progress: bigint,
    workHash: string,
    difficultyHash: string,
    evidenceHash: string
  ] & {
    reportedAt: bigint;
    progress: bigint;
    workHash: string;
    difficultyHash: string;
    evidenceHash: string;
  };

  export type KPIStruct = {
    total: BigNumberish;
    todo: BigNumberish;
    completed: BigNumberish;
    inProgress: BigNumberish;
    cancelled: BigNumberish;
    onSchedule: BigNumberish;
    delayed: BigNumberish;
    overdue: BigNumberish;
    progressSum: BigNumberish;
    averageProgress: BigNumberish;
  };

  export type KPIStructOutput = [
    total: bigint,
    todo: bigint,
    completed: bigint,
    inProgress: bigint,
    cancelled: bigint,
    onSchedule: bigint,
    delayed: bigint,
    overdue: bigint,
    progressSum: bigint,
    averageProgress: bigint
  ] & {
    total: bigint;
    todo: bigint;
    completed: bigint;
    inProgress: bigint;
    cancelled: bigint;
    onSchedule: bigint;
    delayed: bigint;
    overdue: bigint;
    progressSum: bigint;
    averageProgress: bigint;
  };

  export type SubTaskStruct = {
    externalId: BytesLike;
    metadataHash: BytesLike;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
    progress: BigNumberish;
    status: BigNumberish;
    deleted: boolean;
  };

  export type SubTaskStructOutput = [
    externalId: string,
    metadataHash: string,
    createdAt: bigint,
    updatedAt: bigint,
    progress: bigint,
    status: bigint,
    deleted: boolean
  ] & {
    externalId: string;
    metadataHash: string;
    createdAt: bigint;
    updatedAt: bigint;
    progress: bigint;
    status: bigint;
    deleted: boolean;
  };

  export type ContentRecordStruct = {
    recordedBy: AddressLike;
    recordedAt: BigNumberish;
    kind: BigNumberish;
    contentHash: BytesLike;
  };

  export type ContentRecordStructOutput = [
    recordedBy: string,
    recordedAt: bigint,
    kind: bigint,
    contentHash: string
  ] & {
    recordedBy: string;
    recordedAt: bigint;
    kind: bigint;
    contentHash: string;
  };
}

export interface PlaneTaskManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admins"
      | "assignTask"
      | "cancelTask"
      | "contractVersion"
      | "createChildTask"
      | "createSubTask"
      | "createTask"
      | "dAppRecords"
      | "deleteChildTask"
      | "deleteSubTask"
      | "deleteTask"
      | "getAssignedTaskCount"
      | "getAssignedTasks"
      | "getContentCount"
      | "getDAppRecord"
      | "getDailyReport"
      | "getKPI"
      | "getReportCount"
      | "getScheduleStatus"
      | "getSubTask"
      | "getSubTaskCount"
      | "getSubTaskId"
      | "getSubTaskStats"
      | "getSubTasks"
      | "getTask"
      | "getTaskContent"
      | "getTaskId"
      | "isOverdue"
      | "owner"
      | "recordTaskContent"
      | "setAdmin"
      | "submitDailyReport"
      | "submitDailyReportAndSyncAncestors"
      | "taskCount"
      | "transferOwnership"
      | "updateDAppRecord"
      | "updateProgress"
      | "updateSchedule"
      | "updateSubTaskMetadata"
      | "updateSubTaskProgress"
      | "updateSubTaskStatus"
      | "updateTaskMetadata"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminUpdated"
      | "DAppRecordUpdated"
      | "DailyReportSubmitted"
      | "OwnershipTransferred"
      | "SubTaskCreated"
      | "SubTaskDeleted"
      | "SubTaskProgressUpdated"
      | "SubTaskStatusUpdated"
      | "TaskAssigned"
      | "TaskContentRecorded"
      | "TaskCreated"
      | "TaskDeleted"
      | "TaskMetadataUpdated"
      | "TaskProgressUpdated"
      | "TaskScheduleUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "assignTask",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contractVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createChildTask",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubTask",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BytesLike, BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dAppRecords",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteChildTask",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteSubTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssignedTaskCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAssignedTasks",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContentCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDAppRecord",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyReport",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getKPI", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getReportCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getScheduleStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubTaskCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubTaskId",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubTaskStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubTasks",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskContent",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskId",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOverdue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordTaskContent",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDailyReport",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDailyReportAndSyncAncestors",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish[],
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "taskCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateDAppRecord",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProgress",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSchedule",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubTaskMetadata",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubTaskProgress",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSubTaskStatus",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTaskMetadata",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assignTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "contractVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChildTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dAppRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteChildTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteSubTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAssignedTaskCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAssignedTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDAppRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getKPI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getScheduleStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSubTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubTaskCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubTaskId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubTaskStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTaskId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOverdue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordTaskContent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitDailyReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDailyReportAndSyncAncestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDAppRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubTaskMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubTaskProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSubTaskStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTaskMetadata",
    data: BytesLike
  ): Result;
}

export namespace AdminUpdatedEvent {
  export type InputTuple = [account: AddressLike, enabled: boolean];
  export type OutputTuple = [account: string, enabled: boolean];
  export interface OutputObject {
    account: string;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DAppRecordUpdatedEvent {
  export type InputTuple = [
    collection: string,
    id: string,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [collection: string, id: string, updatedBy: string];
  export interface OutputObject {
    collection: string;
    id: string;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyReportSubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    reportId: BigNumberish,
    reporter: AddressLike,
    progress: BigNumberish,
    workHash: BytesLike,
    difficultyHash: BytesLike,
    evidenceHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    reportId: bigint,
    reporter: string,
    progress: bigint,
    workHash: string,
    difficultyHash: string,
    evidenceHash: string
  ];
  export interface OutputObject {
    taskId: bigint;
    reportId: bigint;
    reporter: string;
    progress: bigint;
    workHash: string;
    difficultyHash: string;
    evidenceHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubTaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    subTaskId: BigNumberish,
    externalId: BytesLike,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    subTaskId: bigint,
    externalId: string,
    metadataHash: string
  ];
  export interface OutputObject {
    taskId: bigint;
    subTaskId: bigint;
    externalId: string;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubTaskDeletedEvent {
  export type InputTuple = [taskId: BigNumberish, subTaskId: BigNumberish];
  export type OutputTuple = [taskId: bigint, subTaskId: bigint];
  export interface OutputObject {
    taskId: bigint;
    subTaskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubTaskProgressUpdatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    subTaskId: BigNumberish,
    progress: BigNumberish,
    status: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    subTaskId: bigint,
    progress: bigint,
    status: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    taskId: bigint;
    subTaskId: bigint;
    progress: bigint;
    status: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubTaskStatusUpdatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    subTaskId: BigNumberish,
    status: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    subTaskId: bigint,
    status: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    taskId: bigint;
    subTaskId: bigint;
    status: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAssignedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    previousAssignee: AddressLike,
    newAssignee: AddressLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    previousAssignee: string,
    newAssignee: string
  ];
  export interface OutputObject {
    taskId: bigint;
    previousAssignee: string;
    newAssignee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskContentRecordedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    kind: BigNumberish,
    contentHash: BytesLike,
    recordedBy: AddressLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    kind: bigint,
    contentHash: string,
    recordedBy: string
  ];
  export interface OutputObject {
    taskId: bigint;
    kind: bigint;
    contentHash: string;
    recordedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    externalId: BytesLike,
    creator: AddressLike,
    assignee: AddressLike,
    dueAt: BigNumberish,
    priority: BigNumberish,
    metadataHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    externalId: string,
    creator: string,
    assignee: string,
    dueAt: bigint,
    priority: bigint,
    metadataHash: string
  ];
  export interface OutputObject {
    taskId: bigint;
    externalId: string;
    creator: string;
    assignee: string;
    dueAt: bigint;
    priority: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskDeletedEvent {
  export type InputTuple = [taskId: BigNumberish, deletedBy: AddressLike];
  export type OutputTuple = [taskId: bigint, deletedBy: string];
  export interface OutputObject {
    taskId: bigint;
    deletedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskMetadataUpdatedEvent {
  export type InputTuple = [taskId: BigNumberish, metadataHash: BytesLike];
  export type OutputTuple = [taskId: bigint, metadataHash: string];
  export interface OutputObject {
    taskId: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskProgressUpdatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    progress: BigNumberish,
    status: BigNumberish,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    progress: bigint,
    status: bigint,
    updatedBy: string
  ];
  export interface OutputObject {
    taskId: bigint;
    progress: bigint;
    status: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskScheduleUpdatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    dueAt: BigNumberish,
    priority: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, dueAt: bigint, priority: bigint];
  export interface OutputObject {
    taskId: bigint;
    dueAt: bigint;
    priority: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlaneTaskManager extends BaseContract {
  connect(runner?: ContractRunner | null): PlaneTaskManager;
  waitForDeployment(): Promise<this>;

  interface: PlaneTaskManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  assignTask: TypedContractMethod<
    [taskId: BigNumberish, assignee: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  contractVersion: TypedContractMethod<[], [bigint], "view">;

  createChildTask: TypedContractMethod<
    [
      parentTaskId: BigNumberish,
      childExternalId: BytesLike,
      childMetadataHash: BytesLike,
      assignee: AddressLike,
      dueAt: BigNumberish,
      priority: BigNumberish,
      relationshipExternalId: BytesLike,
      relationshipMetadataHash: BytesLike
    ],
    [[bigint, bigint] & { childTaskId: bigint; subTaskId: bigint }],
    "nonpayable"
  >;

  createSubTask: TypedContractMethod<
    [taskId: BigNumberish, externalId: BytesLike, metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      externalId: BytesLike,
      metadataHash: BytesLike,
      assignee: AddressLike,
      dueAt: BigNumberish,
      priority: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  dAppRecords: TypedContractMethod<
    [arg0: string, arg1: string],
    [string],
    "view"
  >;

  deleteChildTask: TypedContractMethod<
    [
      childTaskId: BigNumberish,
      parentTaskId: BigNumberish,
      subTaskId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  deleteSubTask: TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deleteTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  getAssignedTaskCount: TypedContractMethod<
    [assignee: AddressLike],
    [bigint],
    "view"
  >;

  getAssignedTasks: TypedContractMethod<
    [assignee: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [PlaneTaskManager.TaskStructOutput[]],
    "view"
  >;

  getContentCount: TypedContractMethod<
    [taskId: BigNumberish],
    [bigint],
    "view"
  >;

  getDAppRecord: TypedContractMethod<
    [collection: string, id: string],
    [string],
    "view"
  >;

  getDailyReport: TypedContractMethod<
    [taskId: BigNumberish, reportId: BigNumberish],
    [PlaneTaskManager.DailyReportStructOutput],
    "view"
  >;

  getKPI: TypedContractMethod<
    [assignee: AddressLike],
    [PlaneTaskManager.KPIStructOutput],
    "view"
  >;

  getReportCount: TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;

  getScheduleStatus: TypedContractMethod<
    [taskId: BigNumberish],
    [bigint],
    "view"
  >;

  getSubTask: TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish],
    [PlaneTaskManager.SubTaskStructOutput],
    "view"
  >;

  getSubTaskCount: TypedContractMethod<
    [taskId: BigNumberish],
    [bigint],
    "view"
  >;

  getSubTaskId: TypedContractMethod<
    [taskId: BigNumberish, externalId: BytesLike],
    [bigint],
    "view"
  >;

  getSubTaskStats: TypedContractMethod<
    [taskId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        activeCount: bigint;
        completedCount: bigint;
        progress: bigint;
      }
    ],
    "view"
  >;

  getSubTasks: TypedContractMethod<
    [taskId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [PlaneTaskManager.SubTaskStructOutput[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [PlaneTaskManager.TaskStructOutput],
    "view"
  >;

  getTaskContent: TypedContractMethod<
    [taskId: BigNumberish, contentId: BigNumberish],
    [PlaneTaskManager.ContentRecordStructOutput],
    "view"
  >;

  getTaskId: TypedContractMethod<[externalId: BytesLike], [bigint], "view">;

  isOverdue: TypedContractMethod<[taskId: BigNumberish], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordTaskContent: TypedContractMethod<
    [taskId: BigNumberish, kind: BigNumberish, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  setAdmin: TypedContractMethod<
    [account: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;

  submitDailyReport: TypedContractMethod<
    [
      taskId: BigNumberish,
      progress: BigNumberish,
      workHash: BytesLike,
      difficultyHash: BytesLike,
      evidenceHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  submitDailyReportAndSyncAncestors: TypedContractMethod<
    [
      taskId: BigNumberish,
      progress: BigNumberish,
      workHash: BytesLike,
      difficultyHash: BytesLike,
      evidenceHash: BytesLike,
      parentTaskIds: BigNumberish[],
      subTaskIds: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;

  taskCount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateDAppRecord: TypedContractMethod<
    [collection: string, id: string, jsonPayload: string],
    [void],
    "nonpayable"
  >;

  updateProgress: TypedContractMethod<
    [taskId: BigNumberish, progress: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSchedule: TypedContractMethod<
    [taskId: BigNumberish, dueAt: BigNumberish, priority: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSubTaskMetadata: TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  updateSubTaskProgress: TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish, progress: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateSubTaskStatus: TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTaskMetadata: TypedContractMethod<
    [taskId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "assignTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, assignee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contractVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createChildTask"
  ): TypedContractMethod<
    [
      parentTaskId: BigNumberish,
      childExternalId: BytesLike,
      childMetadataHash: BytesLike,
      assignee: AddressLike,
      dueAt: BigNumberish,
      priority: BigNumberish,
      relationshipExternalId: BytesLike,
      relationshipMetadataHash: BytesLike
    ],
    [[bigint, bigint] & { childTaskId: bigint; subTaskId: bigint }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSubTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, externalId: BytesLike, metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      externalId: BytesLike,
      metadataHash: BytesLike,
      assignee: AddressLike,
      dueAt: BigNumberish,
      priority: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dAppRecords"
  ): TypedContractMethod<[arg0: string, arg1: string], [string], "view">;
  getFunction(
    nameOrSignature: "deleteChildTask"
  ): TypedContractMethod<
    [
      childTaskId: BigNumberish,
      parentTaskId: BigNumberish,
      subTaskId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteSubTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAssignedTaskCount"
  ): TypedContractMethod<[assignee: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAssignedTasks"
  ): TypedContractMethod<
    [assignee: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [PlaneTaskManager.TaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContentCount"
  ): TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDAppRecord"
  ): TypedContractMethod<[collection: string, id: string], [string], "view">;
  getFunction(
    nameOrSignature: "getDailyReport"
  ): TypedContractMethod<
    [taskId: BigNumberish, reportId: BigNumberish],
    [PlaneTaskManager.DailyReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getKPI"
  ): TypedContractMethod<
    [assignee: AddressLike],
    [PlaneTaskManager.KPIStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReportCount"
  ): TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getScheduleStatus"
  ): TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubTask"
  ): TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish],
    [PlaneTaskManager.SubTaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubTaskCount"
  ): TypedContractMethod<[taskId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubTaskId"
  ): TypedContractMethod<
    [taskId: BigNumberish, externalId: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubTaskStats"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        activeCount: bigint;
        completedCount: bigint;
        progress: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubTasks"
  ): TypedContractMethod<
    [taskId: BigNumberish, offset: BigNumberish, limit: BigNumberish],
    [PlaneTaskManager.SubTaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [PlaneTaskManager.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskContent"
  ): TypedContractMethod<
    [taskId: BigNumberish, contentId: BigNumberish],
    [PlaneTaskManager.ContentRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskId"
  ): TypedContractMethod<[externalId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isOverdue"
  ): TypedContractMethod<[taskId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordTaskContent"
  ): TypedContractMethod<
    [taskId: BigNumberish, kind: BigNumberish, contentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<
    [account: AddressLike, enabled: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDailyReport"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      progress: BigNumberish,
      workHash: BytesLike,
      difficultyHash: BytesLike,
      evidenceHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDailyReportAndSyncAncestors"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      progress: BigNumberish,
      workHash: BytesLike,
      difficultyHash: BytesLike,
      evidenceHash: BytesLike,
      parentTaskIds: BigNumberish[],
      subTaskIds: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateDAppRecord"
  ): TypedContractMethod<
    [collection: string, id: string, jsonPayload: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProgress"
  ): TypedContractMethod<
    [taskId: BigNumberish, progress: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSchedule"
  ): TypedContractMethod<
    [taskId: BigNumberish, dueAt: BigNumberish, priority: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSubTaskMetadata"
  ): TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSubTaskProgress"
  ): TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish, progress: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSubTaskStatus"
  ): TypedContractMethod<
    [taskId: BigNumberish, subTaskId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTaskMetadata"
  ): TypedContractMethod<
    [taskId: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminUpdated"
  ): TypedContractEvent<
    AdminUpdatedEvent.InputTuple,
    AdminUpdatedEvent.OutputTuple,
    AdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DAppRecordUpdated"
  ): TypedContractEvent<
    DAppRecordUpdatedEvent.InputTuple,
    DAppRecordUpdatedEvent.OutputTuple,
    DAppRecordUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DailyReportSubmitted"
  ): TypedContractEvent<
    DailyReportSubmittedEvent.InputTuple,
    DailyReportSubmittedEvent.OutputTuple,
    DailyReportSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubTaskCreated"
  ): TypedContractEvent<
    SubTaskCreatedEvent.InputTuple,
    SubTaskCreatedEvent.OutputTuple,
    SubTaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubTaskDeleted"
  ): TypedContractEvent<
    SubTaskDeletedEvent.InputTuple,
    SubTaskDeletedEvent.OutputTuple,
    SubTaskDeletedEvent.OutputObject
  >;
  getEvent(
    key: "SubTaskProgressUpdated"
  ): TypedContractEvent<
    SubTaskProgressUpdatedEvent.InputTuple,
    SubTaskProgressUpdatedEvent.OutputTuple,
    SubTaskProgressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SubTaskStatusUpdated"
  ): TypedContractEvent<
    SubTaskStatusUpdatedEvent.InputTuple,
    SubTaskStatusUpdatedEvent.OutputTuple,
    SubTaskStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAssigned"
  ): TypedContractEvent<
    TaskAssignedEvent.InputTuple,
    TaskAssignedEvent.OutputTuple,
    TaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TaskContentRecorded"
  ): TypedContractEvent<
    TaskContentRecordedEvent.InputTuple,
    TaskContentRecordedEvent.OutputTuple,
    TaskContentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskDeleted"
  ): TypedContractEvent<
    TaskDeletedEvent.InputTuple,
    TaskDeletedEvent.OutputTuple,
    TaskDeletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskMetadataUpdated"
  ): TypedContractEvent<
    TaskMetadataUpdatedEvent.InputTuple,
    TaskMetadataUpdatedEvent.OutputTuple,
    TaskMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskProgressUpdated"
  ): TypedContractEvent<
    TaskProgressUpdatedEvent.InputTuple,
    TaskProgressUpdatedEvent.OutputTuple,
    TaskProgressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskScheduleUpdated"
  ): TypedContractEvent<
    TaskScheduleUpdatedEvent.InputTuple,
    TaskScheduleUpdatedEvent.OutputTuple,
    TaskScheduleUpdatedEvent.OutputObject
  >;

  filters: {
    "AdminUpdated(address,bool)": TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;
    AdminUpdated: TypedContractEvent<
      AdminUpdatedEvent.InputTuple,
      AdminUpdatedEvent.OutputTuple,
      AdminUpdatedEvent.OutputObject
    >;

    "DAppRecordUpdated(string,string,address)": TypedContractEvent<
      DAppRecordUpdatedEvent.InputTuple,
      DAppRecordUpdatedEvent.OutputTuple,
      DAppRecordUpdatedEvent.OutputObject
    >;
    DAppRecordUpdated: TypedContractEvent<
      DAppRecordUpdatedEvent.InputTuple,
      DAppRecordUpdatedEvent.OutputTuple,
      DAppRecordUpdatedEvent.OutputObject
    >;

    "DailyReportSubmitted(uint256,uint256,address,uint8,bytes32,bytes32,bytes32)": TypedContractEvent<
      DailyReportSubmittedEvent.InputTuple,
      DailyReportSubmittedEvent.OutputTuple,
      DailyReportSubmittedEvent.OutputObject
    >;
    DailyReportSubmitted: TypedContractEvent<
      DailyReportSubmittedEvent.InputTuple,
      DailyReportSubmittedEvent.OutputTuple,
      DailyReportSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubTaskCreated(uint256,uint256,bytes32,bytes32)": TypedContractEvent<
      SubTaskCreatedEvent.InputTuple,
      SubTaskCreatedEvent.OutputTuple,
      SubTaskCreatedEvent.OutputObject
    >;
    SubTaskCreated: TypedContractEvent<
      SubTaskCreatedEvent.InputTuple,
      SubTaskCreatedEvent.OutputTuple,
      SubTaskCreatedEvent.OutputObject
    >;

    "SubTaskDeleted(uint256,uint256)": TypedContractEvent<
      SubTaskDeletedEvent.InputTuple,
      SubTaskDeletedEvent.OutputTuple,
      SubTaskDeletedEvent.OutputObject
    >;
    SubTaskDeleted: TypedContractEvent<
      SubTaskDeletedEvent.InputTuple,
      SubTaskDeletedEvent.OutputTuple,
      SubTaskDeletedEvent.OutputObject
    >;

    "SubTaskProgressUpdated(uint256,uint256,uint8,uint8,address)": TypedContractEvent<
      SubTaskProgressUpdatedEvent.InputTuple,
      SubTaskProgressUpdatedEvent.OutputTuple,
      SubTaskProgressUpdatedEvent.OutputObject
    >;
    SubTaskProgressUpdated: TypedContractEvent<
      SubTaskProgressUpdatedEvent.InputTuple,
      SubTaskProgressUpdatedEvent.OutputTuple,
      SubTaskProgressUpdatedEvent.OutputObject
    >;

    "SubTaskStatusUpdated(uint256,uint256,uint8,address)": TypedContractEvent<
      SubTaskStatusUpdatedEvent.InputTuple,
      SubTaskStatusUpdatedEvent.OutputTuple,
      SubTaskStatusUpdatedEvent.OutputObject
    >;
    SubTaskStatusUpdated: TypedContractEvent<
      SubTaskStatusUpdatedEvent.InputTuple,
      SubTaskStatusUpdatedEvent.OutputTuple,
      SubTaskStatusUpdatedEvent.OutputObject
    >;

    "TaskAssigned(uint256,address,address)": TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;
    TaskAssigned: TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;

    "TaskContentRecorded(uint256,uint8,bytes32,address)": TypedContractEvent<
      TaskContentRecordedEvent.InputTuple,
      TaskContentRecordedEvent.OutputTuple,
      TaskContentRecordedEvent.OutputObject
    >;
    TaskContentRecorded: TypedContractEvent<
      TaskContentRecordedEvent.InputTuple,
      TaskContentRecordedEvent.OutputTuple,
      TaskContentRecordedEvent.OutputObject
    >;

    "TaskCreated(uint256,bytes32,address,address,uint64,uint8,bytes32)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskDeleted(uint256,address)": TypedContractEvent<
      TaskDeletedEvent.InputTuple,
      TaskDeletedEvent.OutputTuple,
      TaskDeletedEvent.OutputObject
    >;
    TaskDeleted: TypedContractEvent<
      TaskDeletedEvent.InputTuple,
      TaskDeletedEvent.OutputTuple,
      TaskDeletedEvent.OutputObject
    >;

    "TaskMetadataUpdated(uint256,bytes32)": TypedContractEvent<
      TaskMetadataUpdatedEvent.InputTuple,
      TaskMetadataUpdatedEvent.OutputTuple,
      TaskMetadataUpdatedEvent.OutputObject
    >;
    TaskMetadataUpdated: TypedContractEvent<
      TaskMetadataUpdatedEvent.InputTuple,
      TaskMetadataUpdatedEvent.OutputTuple,
      TaskMetadataUpdatedEvent.OutputObject
    >;

    "TaskProgressUpdated(uint256,uint8,uint8,address)": TypedContractEvent<
      TaskProgressUpdatedEvent.InputTuple,
      TaskProgressUpdatedEvent.OutputTuple,
      TaskProgressUpdatedEvent.OutputObject
    >;
    TaskProgressUpdated: TypedContractEvent<
      TaskProgressUpdatedEvent.InputTuple,
      TaskProgressUpdatedEvent.OutputTuple,
      TaskProgressUpdatedEvent.OutputObject
    >;

    "TaskScheduleUpdated(uint256,uint64,uint8)": TypedContractEvent<
      TaskScheduleUpdatedEvent.InputTuple,
      TaskScheduleUpdatedEvent.OutputTuple,
      TaskScheduleUpdatedEvent.OutputObject
    >;
    TaskScheduleUpdated: TypedContractEvent<
      TaskScheduleUpdatedEvent.InputTuple,
      TaskScheduleUpdatedEvent.OutputTuple,
      TaskScheduleUpdatedEvent.OutputObject
    >;
  };
}
